
name: CI/CD Workflow

on:
  push:
    branches: [master]
    paths-ignore: ["docs/**"]

  pull_request:
    branches: [master]
    paths-ignore: ["docs/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: Install `zstash` Package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run Tests
      run: |
        cd tests
        python -m unittest
